---
- name: Set SSH Options
  hosts: all
  become: yes
  vars:
    description: Limit SSH MaxAuthTries, set DenyUsers for root, set ClientAliveInterval Timeout

  tasks:

    - name: Limit SSH MaxAuthTries
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MaxAuthTries'
        line: MaxAuthTries 4
        state: present
        backup: yes
      notify:
        - 'Restart sshd'
        - "Writing to /Changelog"    
        
    - name: Deny root
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^DenyUsers'
        line: DenyUsers root
        state: present
        backup: yes
      notify:
        - 'Restart sshd'
        - "Writing to /Changelog"

    - name: Set ClientAliveInterval Timeout
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^ClientAliveInterval'
        line: ClientAliveInterval 300
        state: present
        backup: yes
      notify:
        - 'Restart sshd'
        - "Writing to /Changelog"

  handlers:
    - name: Restart sshd
      listen: 'Restart sshd'
      service:
        name: sshd
        state: restarted

    - name: Update /Changelog
      include_tasks: changelog.yml
      listen: "Writing to /Changelog"

